//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoSoft.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServicioSoap")]
    public interface ServicioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iniciar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Iniciar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cerrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Cerrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaGeneral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultaGeneral(string Tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarServicio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarServicio(string idservicio, string mesa, string horaLlegada, string horaSalida, string nombreCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarCliente(string nombre, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarProducto(string nombreProducto, string tipoComida, string precio, string descripcion, string costo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarOrdenes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarOrdenes(string nombreCliente, string numeroDeMesa, string numeroOrden, string hora, string nombreProducto, string cantidad, string precio, string claveEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarDomicilio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarDomicilio(string NoServicio, string nombreCliente, string telefono, string domicilio, string Orden, string Cantidad, string Costo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarReceta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarReceta(string nombreProducto, string ingrediente, string cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarProveedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarProveedor(string idProveedor, string nombreEmpresa, string telefono, string direccion, string email, string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarCompras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarCompras(string idOrden, string idProveedor, string idProducto, string fechaCompra, string importe, string cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarReservacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarReservacion(string idReservacion, string nombreCliente, string mesa, string fechaHora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarPersonal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarPersonal(string idEmpleado, string nombreEmpleado, string telefono, string direccion, string email, string puesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarPromocion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarPromocion(string numeroPromocion, string descripcion, string fechaInicio, string fechaFin, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ingresarUsuario(string nombreUsuario, string password, string puesto, string Nombre, string Direccion, string Telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarServicio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarServicio(string mesa, string horaLlegada, string horaSalida, string nombreCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarCliente(string nombre, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarProducto(string nombreProducto, string tipoComida, string precio, string descripcion, string costo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarOrdenes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarOrdenes(string nombreCliente, string numeroDeMesa, string numeroOrden, string hora, string nombreProducto, string cantidad, string precio, string claveEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDomicilio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarDomicilio(string nombreCliente, string telefono, string domicilio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarReceta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarReceta(string nombreProducto, string ingrediente, string cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarProveedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarProveedor(string idProveedor, string nombreEmpresa, string telefono, string direccion, string email, string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarCompras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarCompras(string idOrden, string idProveedor, string idProducto, string fechaCompra, string importe, string cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarReservacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarReservacion(string idReservacion, string nombreCliente, string mesa, string fechaHora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPersonal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarPersonal(string idEmpleado, string nombreEmpleado, string telefono, string direccion, string email, string puesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPromocion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarPromocion(string numeroPromocion, string descripcion, string fechaInicio, string fechaFin, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminarUsuario(string nombreUsuario, string password, string puesto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSoapChannel : RestoSoft.ServiceReference1.ServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSoapClient : System.ServiceModel.ClientBase<RestoSoft.ServiceReference1.ServicioSoap>, RestoSoft.ServiceReference1.ServicioSoap {
        
        public ServicioSoapClient() {
        }
        
        public ServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Iniciar() {
            base.Channel.Iniciar();
        }
        
        public void Cerrar() {
            base.Channel.Cerrar();
        }
        
        public System.Data.DataSet ConsultaGeneral(string Tabla) {
            return base.Channel.ConsultaGeneral(Tabla);
        }
        
        public string ingresarServicio(string idservicio, string mesa, string horaLlegada, string horaSalida, string nombreCliente) {
            return base.Channel.ingresarServicio(idservicio, mesa, horaLlegada, horaSalida, nombreCliente);
        }
        
        public string ingresarCliente(string nombre, string telefono) {
            return base.Channel.ingresarCliente(nombre, telefono);
        }
        
        public string ingresarProducto(string nombreProducto, string tipoComida, string precio, string descripcion, string costo) {
            return base.Channel.ingresarProducto(nombreProducto, tipoComida, precio, descripcion, costo);
        }
        
        public string ingresarOrdenes(string nombreCliente, string numeroDeMesa, string numeroOrden, string hora, string nombreProducto, string cantidad, string precio, string claveEmpleado) {
            return base.Channel.ingresarOrdenes(nombreCliente, numeroDeMesa, numeroOrden, hora, nombreProducto, cantidad, precio, claveEmpleado);
        }
        
        public string ingresarDomicilio(string NoServicio, string nombreCliente, string telefono, string domicilio, string Orden, string Cantidad, string Costo) {
            return base.Channel.ingresarDomicilio(NoServicio, nombreCliente, telefono, domicilio, Orden, Cantidad, Costo);
        }
        
        public string ingresarReceta(string nombreProducto, string ingrediente, string cantidad) {
            return base.Channel.ingresarReceta(nombreProducto, ingrediente, cantidad);
        }
        
        public string ingresarProveedor(string idProveedor, string nombreEmpresa, string telefono, string direccion, string email, string rfc) {
            return base.Channel.ingresarProveedor(idProveedor, nombreEmpresa, telefono, direccion, email, rfc);
        }
        
        public string ingresarCompras(string idOrden, string idProveedor, string idProducto, string fechaCompra, string importe, string cantidad) {
            return base.Channel.ingresarCompras(idOrden, idProveedor, idProducto, fechaCompra, importe, cantidad);
        }
        
        public string ingresarReservacion(string idReservacion, string nombreCliente, string mesa, string fechaHora) {
            return base.Channel.ingresarReservacion(idReservacion, nombreCliente, mesa, fechaHora);
        }
        
        public string ingresarPersonal(string idEmpleado, string nombreEmpleado, string telefono, string direccion, string email, string puesto) {
            return base.Channel.ingresarPersonal(idEmpleado, nombreEmpleado, telefono, direccion, email, puesto);
        }
        
        public string ingresarPromocion(string numeroPromocion, string descripcion, string fechaInicio, string fechaFin, string nombre) {
            return base.Channel.ingresarPromocion(numeroPromocion, descripcion, fechaInicio, fechaFin, nombre);
        }
        
        public string ingresarUsuario(string nombreUsuario, string password, string puesto, string Nombre, string Direccion, string Telefono) {
            return base.Channel.ingresarUsuario(nombreUsuario, password, puesto, Nombre, Direccion, Telefono);
        }
        
        public string eliminarServicio(string mesa, string horaLlegada, string horaSalida, string nombreCliente) {
            return base.Channel.eliminarServicio(mesa, horaLlegada, horaSalida, nombreCliente);
        }
        
        public string eliminarCliente(string nombre, string telefono) {
            return base.Channel.eliminarCliente(nombre, telefono);
        }
        
        public string eliminarProducto(string nombreProducto, string tipoComida, string precio, string descripcion, string costo) {
            return base.Channel.eliminarProducto(nombreProducto, tipoComida, precio, descripcion, costo);
        }
        
        public string eliminarOrdenes(string nombreCliente, string numeroDeMesa, string numeroOrden, string hora, string nombreProducto, string cantidad, string precio, string claveEmpleado) {
            return base.Channel.eliminarOrdenes(nombreCliente, numeroDeMesa, numeroOrden, hora, nombreProducto, cantidad, precio, claveEmpleado);
        }
        
        public string eliminarDomicilio(string nombreCliente, string telefono, string domicilio) {
            return base.Channel.eliminarDomicilio(nombreCliente, telefono, domicilio);
        }
        
        public string eliminarReceta(string nombreProducto, string ingrediente, string cantidad) {
            return base.Channel.eliminarReceta(nombreProducto, ingrediente, cantidad);
        }
        
        public string eliminarProveedor(string idProveedor, string nombreEmpresa, string telefono, string direccion, string email, string rfc) {
            return base.Channel.eliminarProveedor(idProveedor, nombreEmpresa, telefono, direccion, email, rfc);
        }
        
        public string eliminarCompras(string idOrden, string idProveedor, string idProducto, string fechaCompra, string importe, string cantidad) {
            return base.Channel.eliminarCompras(idOrden, idProveedor, idProducto, fechaCompra, importe, cantidad);
        }
        
        public string eliminarReservacion(string idReservacion, string nombreCliente, string mesa, string fechaHora) {
            return base.Channel.eliminarReservacion(idReservacion, nombreCliente, mesa, fechaHora);
        }
        
        public string eliminarPersonal(string idEmpleado, string nombreEmpleado, string telefono, string direccion, string email, string puesto) {
            return base.Channel.eliminarPersonal(idEmpleado, nombreEmpleado, telefono, direccion, email, puesto);
        }
        
        public string eliminarPromocion(string numeroPromocion, string descripcion, string fechaInicio, string fechaFin, string nombre) {
            return base.Channel.eliminarPromocion(numeroPromocion, descripcion, fechaInicio, fechaFin, nombre);
        }
        
        public string eliminarUsuario(string nombreUsuario, string password, string puesto) {
            return base.Channel.eliminarUsuario(nombreUsuario, password, puesto);
        }
    }
}
